### ISSUE TITLE
Placing walls is possible at the very end of the Hitscan round

### ISSUE THREAD

**Issue by kb173** [lizrad/recursio#83] opened 2021-10-13 14:42 UTC
seems like there are a few frames at the end of the round where the weapon (ghost_index) has already been incremented, so the next weapon is used

(not sure if this applies to the client, the server, or both)

**Comment by AmonShokhinAhmed** [comment] 2021-11-11 11:57
Closing because I cannot reproduce it anymore (and I also am quite sure that this cannot be possible anymore).

**Closed by AmonShokhinAhmed** 2021-11-11 11:57 UTC
Labels: bug, needs testing
